export { default as auth } from './auth'
export { default as login } from './login'
export { default as register } from './register'
export { default as user } from './user'
// export { default as router } from './reactRouter'
